const THEME_ACCENT_COLOR = "#2C3E50";
const THEME_BACKGROUND_COLOR = "#555555";
const THEME_WHITE = "white";

const ELE_SHADOW = {
  filter: `drop-shadow(0 0 .1rem ${THEME_BACKGROUND_COLOR})`,
};

export { THEME_ACCENT_COLOR, THEME_BACKGROUND_COLOR, THEME_WHITE, ELE_SHADOW };
